name: Heroku deploy

on:
  workflow_dispatch:
    inputs:
      name:
        default: 'World'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
