# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - rate-my-phone

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  WEBAPP_NAME: 'rate-my-phone'
  RESOURCE_GROUP: 'rate-my-phone'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: Create firebase json
        run: |
          echo ${{ env.GOOGLE_CREDENTIALS }} >> ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Configure deployment and runtime settings on the webapp
        run: |
          az configure --defaults ${{ env.RESOURCE_GROUP }}
          az webapp config appsettings --name ${{ env.WEBAPP_NAME }} --settings \
              SCM_DO_BUILD_DURING_DEPLOYMENT=true \
              FLASK_ENV=production
          az webapp config set --name ${{ env.WEBAPP_NAME }} \
            --startup-file "gunicorn --bind=0.0.0.0 --timeout 600 main.app:rate_my_phone_app"

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'rate-my-phone'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8D35394FE9AC45649F6067AE0F67FA48 }}
